import type { Metadata } from "next";
import { Providers } from "../global/providers";
import { fonts } from "../global/assets/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={(fonts.poppins.variable, fonts.inter.variable)}>
      <head></head>
      <body
        style={{
          background:
            "linear-gradient(158deg, rgba(255,179,0,1) 31%, rgba(212,194,25,1) 77%, rgba(234,255,104,1) 100%)",
          height: "100vh",
          width: "100%",
          color: "#0f172a",
        }}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
